### ISSUE TITLE
PR #22 breaks cluster name in console

### ISSUE THREAD

**Issue by jabbrwcky** [CloudHealth/helm#28]
Hi, the change regarding the cluster name breaks my cluster name in the console on update
<img width="428" alt="Screenshot 2022-04-05 at 09 26 00" src="https://user-images.githubusercontent.com/909640/161701255-605a31a6-a791-48df-93a6-f42e970ac047.png">

It neglects that the secret contents are base64 decoded before being used as ENV variables.

 The second cluster name in the screenshot is the first one Base64-encoded.

```shell
$> echo 'c2MtZGV2ZWxvcG1lbnQy' | base64 -d -
sc-development2
```

#27 fixes this

**Comment by gm-cht** [comment]
Fixed/Merged. Thank you for the PR.
