### ISSUE TITLE
Additional environment variables support for container specs

### ISSUE THREAD

**Issue by paunis** [CloudHealth/helm#46]
Now there are  only 4 environment variables that can be set in container specs: CHT_API_TOKEN, CHT_CLUSTER_NAME, CHT_INTERVAL and CHT_JVM_MEM. Is it possible to implement support for additional environment variables? Something like :

(values.yaml)
...
  env: []
	- name: <ENV_VAR_NAME>
	  value: <ENV_VAR_VALUE>

(deployment.yaml)
...
	containers:
	...
	env:
		- name: CHT_API_TOKEN
			valueFrom:
			secretKeyRef:
				name: {{ include "cloudhealth-collector.secretName" . }}
				key: apiToken
		- name: CHT_CLUSTER_NAME
			value: {{.Values.clusterName | required "A valid clusterName required!" | quote }}
		- name: CHT_INTERVAL
			value: {{ .Values.collectionIntervalSecs | quote }}
		- name: CHT_JVM_MEM
			value: {{ .Values.jvmMemory }}
		{{- toYaml .Values.env | nindent 12 }} 
	...

**Comment by gm-cht** [comment]
Interesting. I am wondering what your use case for env variables is? would it be labels of some sort? Wouldn't the existing `customLabels` cover that scenario?

**Comment by paunis** [comment]
We have a centralized cluster which needs to route traffic through a proxy in order to access the clusters in some regions. In order to have that we need to set additional options for JAVA like http.proxyHost / http.proxPort / https.proxyHost / https.proxyPort. For this I modified the deployment.yaml in templates adding
...
 {{- toYaml .Values.env | nindent 12 }}
and in values.yaml we added
...
env:
  - name: JAVA_OPTS
    value: -Dhttp.proxyHost=xx -Dhttp.proxyPort=xx -Dhttp.nonProxyHosts="xx" -Dhttps.proxyHost=xx -Dhttps.proxyPort=xx -Dhttps.nonProxyHosts="xx"

**Comment by gm-cht** [comment]
Added support for this in Helm Chart version 1.1.2
