### ISSUE TITLE
Pod logs Env variables errors after deploying with values.yaml file

### ISSUE THREAD

**Issue by bcdady** [CloudHealth/helm#61]
I applied 2 custom values.yaml files and used the helmfile tool to successfully deploy the collector to a (dev) cluster.

I specified values for the `apiToken` and `clusterName` keys, and when I review the Environment details for the running pod, I can see the following env vars:

```shell
CHT_API_TOKEN: secretKeyRef(cloudhealth-config.apiToken) 
CHT_CLUSTER_NAME: cluster-dev
CHT_INTERVAL: 900
CHT_JVM_MEM: -Xmx891M
```

However, once the new pod is running, it logs these error messages:

```shell
E, [{timestamp} #10] ERROR -- : Could not open an output stream to the collection API: containers-api.edge.cloudhealthtech.com

E, [{timestamp} #10] ERROR -- : ATTENTION: The most common cause of this error is that the [CHT_API_TOKEN] or [CHT_CLUSTER_NAME] environment variables were not configured properly as part of agent deployment. Please check your full configuration, including the API token and the cluster name. After your config has been fixed, please wait 15 minutes for the changes to take effect, and collection to resume.

D, [{timestamp} #10] DEBUG -- : sleeping for 10
```

I noticed that the value I retrieved from the `cloudhealth-config` secret did not match the ApiToken string I provided in the helm chart. So I manually updated it, but the same errors show in the pod logs, even after restarting the pod.

**Comment by bcdady** [comment]
@ipgv, @kscherme, and/or @pjiten Do you perhaps have any insight to any issues with using values.yaml files or helmfile, or any other edge case that might relate to the Env vars appearing to be set correctly, but then seeing these "CHT" env var errors in the logs?

I'm guessing this might be a helpful clue ... here's what the CHT variables look like from the shell in the pod:
```shell
bash-5.1$ printenv | grep CHT
CHT_API_TOKEN=�N�oV���y�����5ӏ7��������uu��yݶi��
CHT_INTERVAL=900
CHT_JVM_MEM=-Xmx891M
CHT_CLUSTER_NAME=cluster-dev
```

**Comment by bcdady** [comment]
I shelled into a running `cloudhealth-collector` pod and set the CHT_API_TOKEN to the apiToken string displayed to me in the CloudHealth portal.
I continue to see the same error messages in the pod logs.

Details:
```shell
$ export CHT_API_TOKEN=<apiToken-string>
$ printenv | grep CHT
CHT_API_TOKEN=<apiToken-string>
CHT_INTERVAL=900
CHT_JVM_MEM=-Xmx891M
CHT_CLUSTER_NAME=cluster-dev
```

After waiting for several subsequent cycles, the logs continue (validated by seeing newer timestamps in log messages) to see the same ERROR messages as shared above.

**Comment by kscherme** [comment]
Hello!  Just to make sure that you are using the correct API token - did you get the string from the CloudHealth UI?  This API key should be found in the `Setup` section on the `Clusters` page listed under `Containers`.  If you select `Add cluster via Helm`, then the popup should contain your key.  

This key is no the same as the CHT User API or configuration key.

**Comment by bcdady** [comment]
Hi @kscherme Yes, I got the `CHT_API_TOKEN` from the popup with the heading "Add Kubernetes Cluster (via Helm)"

```text
Step 1: Create two environment variables with your unique cluster name and given API token:

# Linux
$ export CHT_API_TOKEN=<Our ApiToken>
$ export CHT_CLUSTER_NAME=<Unique Cluster Name>
```

**Comment by kscherme** [comment]
Hi @bcdady, great!  It looks like you have the environment variables set up correctly, so I am guessing the problem must be coming from elsewhere.  Please work with CloudHealth technical support- they should have more information on what may be going wrong.  Thank you!

**Comment by bcdady** [comment]
Hi again @kscherme

It seems these symptoms are at least in part related to changes between versions 2.0.0 and 2.0.2.
After rolling back my prior helm deployment (v2.0.0 with image tag [1191](https://github.com/CloudHealth/helm/blob/main/cloudhealth-collector-image-docs/CHANGELOG.md) and applying again, helm pulled and deployed v2.0.2 (with with image tag [1203](https://github.com/CloudHealth/helm/blob/1d35f7732ec5fc23e8f5c2334766bcdf305fcab0/cloudhealth-collector/values.yaml#L18), < as is since specified in values.yaml).

Now that I can see the `CHT_API_TOKEN` env variable contains a properly decoded apiToken, I am more confident that the environment variables are set correctly. However, even though I can independently validate this apiToken via these steps ([Validate Collector Agent Connectivity](https://help.cloudhealthtech.com/container-governance/troubleshoot-kubernetes-configuration-issues/#validate-collector-agent-connectivity); pasted below for more convenient reference), the pod continues to emit the same error messages as before.

The related support case has been open for nearly a month. Any additional attention you can share to help resolve this is greatly appreciated.

> **Validate Collector Agent Connectivity**
> 
> To validate collector agent connectivity to our own collection endpoint, run the following commands:
> 
> Use nmap or netcat to ping port 443
> 
> `nmap -p 443 api.cloudhealthtech.com`
> 
> `nc -zv api.cloudhealthtech.com 443`
> 
> Run CURL commands against the collection endpoint manually:
> 
> `curl -v -X GET https://containers-api.edge.cloudhealthtech.com/api/v1/health` to request the collection health endpoint.
> The expected response: {"status":"healthy","time":"Fri, 29 Jan 2021 22:48:10 GMT"}
> 
> `curl --header "Content-Type: application/json" --request POST --data '{"auth_token":"INSERT_AUTHENTICATION_TOKEN_HERE","cluster_id":"INSERT_CLUSTER_ID_HERE"}' https://containers-api.edge.cloudhealthtech.com/v1/containers/kubernetes/state` to mock the exact request made by the collector agent (except without any k8s data cache payload). Replace the auth_token and the cluster_id as necessary.
> The expected response (since we sent no payload): {"result":null}
>
