### ISSUE TITLE
CHANGELOG

### ISSUE THREAD

**Issue by mazay** [CloudHealth/helm#65]
We really need a changelog for the `cloudhealth-collector` helm chart to have a better understanding of what new releases bring.

**Comment by csmithfwi** [comment]
Agreed, I am trying to figure out if there is any use in upgrading `cloudhealth-collector` in my EKS clusters.

**Comment by kscherme** [comment]
Thank you for the feedback!  We have established a release log using the GitHub releases functionality: https://github.com/CloudHealth/helm/releases.  We will keep this up to date with each chart change.
