### ISSUE TITLE
CloudHealth Chart do not allow custom annotations for deployment

### ISSUE THREAD

**Issue by mozz-lx** [CloudHealth/helm#68]
Hello CloudHealth team.

The company where I'm working has a very strict admission controller policy that enforces a set of annotations and labels for deployments.

The current values.yaml file does not provide the option to include those custom annotations. Can you include an alternative for it? I have sent this [PR](https://github.com/CloudHealth/helm/pull/67) for your consideration.

Marco.

**Comment by kscherme** [comment]
Thank you for your contribution!  Your changes are in the new release: https://github.com/CloudHealth/helm/releases/tag/cloudhealth-collector-2.0.12
