### ISSUE TITLE
In Cluster-Role-Binding, ServiceAccount should be bind to Namespace

### ISSUE THREAD

**Issue by jderuere** [CloudHealth/helm#7]
default should be changed to {{ .Release.Namespace }}:
https://github.com/CloudHealth/helm/blob/main/cloudhealth-collector/templates/clusterrolebinding.yaml#L16

As it cause the pod failing to fetch node information.

**Comment by pkchavva** [comment]
Hi @jderuere thank you for your contribution!

 As this is the first contribution to our repo, we are checking on the best way to proceed on how we can accept and get these incorporated into our Helm repo.
 
 I will get back to you in a few days.
 
 Best,
 Pavan Chavva.
 CloudHealth | PM for Kubernetes Optimization

**Comment by gm-cht** [comment]
Being addressed as part of PR https://github.com/CloudHealth/helm/pull/18

**Comment by gm-cht** [comment]
Fixed in version 1.0.1 of the helm chart
