### ISSUE TITLE
Unable to install cloudhealth-collector releases beyond 2.0.4

### ISSUE THREAD

**Issue by sharkeyl** [CloudHealth/helm#77]
I am unable to install cloudhealth-collector releases beyond 2.0.4. It looks like later releases (including 3.2.0, the latest) have not been uploaded to the repository described in the usage steps: 
```
$ helm repo add cloudhealth https://cloudhealth.github.io/helm/
$ helm upgrade --install cloudhealth-collector cloudhealth/cloudhealth-collector --version 3.2.0 --namespace kube-system --values values.yaml
Error: failed to download "cloudhealth/cloudhealth-collector" at version "3.2.0"
```

It is difficult to view the changes that are being made in the chart, requiring inspection of each PR/commit to view changes. 

I have two requests: 

1. Automate the publishing of your Helm charts when a new version is merged to main.
2. Either maintain a CHANGELOG, automate creation of GitHub releases, or ensure git commit messages are in a consistent format. This will make it significantly easier for users of the chart to evaluate the changes made and impact on their system.

Thanks in advance

**Comment by kscherme** [comment]
Thank you for the feedback! We have established a release log using the GitHub releases functionality: https://github.com/CloudHealth/helm/releases and took your advice to automate the publishing of our Helm charts when a new version is merged to main.  The newest version that we have released is `2.0.11`.
