### ISSUE TITLE
Documentation upgrade request: apiToken

### ISSUE THREAD

**Issue by tomashejatko** [CloudHealth/helm#95]
Hello,

apiToken parameter is described as the required parameter in values.yaml, but it is not completely true.  If you don't use it, then the secret file is not created in https://github.com/CloudHealth/helm/blob/440d967ae5e510748d05896a0e47314059569210/charts/cloudhealth-collector/templates/secrets.yaml#L6. So better description would be something as: "use apiToken parameter or create a secret with the name specified by secretName parameter".

Originally I wanted to request a feature to create a secret file on our own, our systems are not able to pass the apiToken parameter safely to the Helm chart, but we are able to create a secret manifest on other part of infra provisioning system. Now I have discovered that this feature is already here, only not well documented :)

Thank you

**Comment by kscherme** [comment]
Thank you for bringing this to our attention.  Here is the pull request with this update if you would like to take a look and add feedback - https://github.com/CloudHealth/helm/pull/96.
