### ISSUE TITLE
Missing Image tag update to 1360 in latest release of cloudhealth-collector-4.0.0

### ISSUE THREAD

**Issue by pushpamahadeva** [CloudHealth/helm#98]
**Why we need this changes?**
As part of  latest release of cloudhealth-collector-4.0.0, missing update on image-tag to 1360.

Hence pods were not coming healthy, stating like
In container with argument (- upload_k8s_state_v4) not found.

**Comment by pushpamahadeva** [comment]
I made a change for image-tag but not able create pull request

`pushpalatha@pushpas-MacBook-Pro cloudhealth-collector % git push origin image-tag-update     
ERROR: Permission to CloudHealth/helm.git denied to pushpamahadeva.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
`

**Comment by JoshuaJackson-jobvite** [comment]
Pr created for this change. In the case outside contributors can't create a pr in the repo directly, so you need to fork the repo and then create the changes in your fork @pushpamahadeva. Then you do a pr from your repo to this one.

**Comment by justdan96** [comment]
Looks like this was fixed via https://github.com/CloudHealth/helm/pull/99

**Comment by JoshuaJackson-jobvite** [comment]
@pushpamahadeva can you or @bswetalina close this as per @justdan96's comment the pr was merged in #99 so this issue can be closed.

**Comment by pushpamahadeva** [comment]
issue addressed already
